services:
  tbamud:
    build: .
    ports:
      - "0.0.0.0:42067:42067"
    volumes:
      - ./lib/plrfiles:/app/lib/plrfiles
      - ./lib/plrobjs:/app/lib/plrobjs
      - ./lib/plrvars:/app/lib/plrvars
      - ./log:/app/log
    restart: unless-stopped

